version: 2.1

orbs:
  node: circleci/node@4.7

executors:
  main:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/MileMarker10/apollo-component-library/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  ci-v16:
    executor: main
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests

workflows:
  sample:
    jobs:
      - ci-v16
      # Testing code
      - node/test:
          version: '16.10'
          pkg-manager: yarn
      - node/test:
          version: '14.17'
          pkg-manager: yarn

      # Linting code
      - node/run:
          version: '16.10'
          pkg-manager: yarn
          yarn-run: lint
      - node/run:
          version: '14.17'
          pkg-manager: yarn
          yarn-run: lint
