version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  CI v16:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test && yarn run lint && yarn run build
          name: Run YARN tests

workflows:
  sample:
    jobs:
      - CI v16
      # Testing code
      - node/test:
          version: '16.10'
          pkg-manager: yarn
      - node/test:
          version: '14.17'
          pkg-manager: yarn

      # Linting code
      - node/run:
          version: '16.10'
          pkg-manager: yarn
          yarn-run: lint
      - node/run:
          version: '14.17'
          pkg-manager: yarn
          yarn-run: lint
